var new_lang = {
    lt1: 'Ordinați sunet gratuit',
    lt2: 'Cum acționează «Tinedol»',
    lt3: 'Efectivitatea',
    lt4: 'Comentarii',
    lt5: 'O metodă simplă de a birui ciuperca, mîncărime și crăpături!',
    lt6: 'Tratează ciuperca tălpilor și unghiilor',
    lt7: 'Înlătură mîncărimea și descuamarea',
    lt8: 'Înlătură sudoarea și mirosul neplăcut',
    lt9: 'Vindecă fisurile de pe tălpi',
    lt10: 'REDUCERE',
    lt11: '-50%',
    lt12: 'Ediție limitată!<br>Grăbiți-vă!<br> Doar <span class="product-how-much"><span class="lastpack">5</span> pachete</span> <br>cu preț special!',
    lt13: 'Pînă la sfîrșitul promoției a rămas:',
    lt14: '00',
    lt15: 'Ore',
    lt16: '25',
    lt17: 'Minute',
    lt18: '59',
    lt19: 'Secunde',
    lt20: 'Prețul integral:',
    lt21: 'Prețul cu reducere',
    lt22: 'Comandă',
    lt23: 'Datele dumneavoastră sunt protejate',
    lt24: '<span class="title2-span1">Credeți că ciuperca a trecut pe alături?</span> Dacă ați observat măcar un symptom la dumneavoastră,<br> atunci puteți începe tratamentul de astăzi',
    lt25: 'Miros neplăcut',
    lt26: 'Crăpături și descuamare',
    lt27: 'Forma neregulată a unghiei',
    lt28: 'Unghia devine <br>cafenie sau galbenă',
    lt29: 'Brazde și pete <br>albe pe unghie',
    lt30: 'Mîncărime și sensație de opăreală',
    lt31: 'Vezicule pe tălpi',
    lt32: 'Amorțire și furnicături',
    lt33: ' îngroșarea locală <br>a pielii în regiunea tălpii',
    lt34: 'Ce se va întîmpla dacă nu veți lecui ciuperca tălpii',
    lt35: 'Conform datelor statistice fiecare al cincilea locuitor a Rusiei suferă de candidoză.<br> Încălțăminte închisă strînsă, șosete sintetice, saune, băi publice, bazine.<br> <span class="stage__span1">În perioada verii se mai adaugă plajele, parcurile, unde mulți umblă cu piciorul gol.<br> Toate acestea aduc la boli strașnice!</span> Stop!',
    lt36: 'Etapa 1:',
    lt37: '<i></i>Descuamare',
    lt38: '<i></i>Mincărime',
    lt39: '<i></i>Nivel înalt de transpirație',
    lt40: '<i></i>Miros neplăcut',
    lt41: '<i></i>Discomfort',
    lt42: 'Etapa 2:',
    lt43: '<i></i>Ciuperca unghiilor',
    lt44: '<i></i>Crăpături adînci',
    lt45: '<i></i>Transpirație abundentă și mîncărime',
    lt46: '<i></i>Miros înțepător permanent',
    lt47: '<i></i>Unghii galbene și fragile',
    lt48: '<i></i>Piele “moartă” și aspră',
    lt49: '<i></i>Un discomfort puternic <br>în timpul mersului',
    lt50: 'Etapa 3:',
    lt51: '<i></i>Descuamare și măncărime <br>între degete',
    lt52: '<i></i>Ulcere și crăpături <br>adănci',
    lt53: '<i></i>Durere',
    lt54: '<i></i>Puroi',
    lt55: '<i></i>Pierderea unghiilor',
    lt56: '<span class="stage__main-block-span">Dacă să nu lecuiți tălpile, se poate începe evoluția unei boli periculoase!</span><br> Imaginați-vă, ă acestea sunt piciorele dumneavoastră! Ați dori să aveți asemenea tălpi?<br> veți spune nu!',
    lt57: 'Cum acționează <span class="title4-span1">crema «Tinedol»?</span>',
    lt58: '<span class="work__span1">Prin folosirea regulată, «Tinedol» vă lipsește deodată de cîteva probleme.</span> Componentele active ce intră în consistența sa efectiv înlătură',
    lt59: 'Ciuperca',
    lt60: 'Mirosul',
    lt61: 'Transpirația',
    lt62: 'Crăpăturile',
    lt63: '<span class="consist__text--b">Klimbazol-ul</span> — ameliorează dezvoltarea drojdiilor și ciupercilor. Tratează mîncărimea. Are efect destructibil asupra ciupercii.',
    lt64: '<span class="consist__text--b">Farnezol</span> — “deconectează” glandele sudoripare. Dezinfectează, usucă, dă o aromă plăcută pentru o lungă perioadă de timp.<span class="consist__text--b">Propolis </span> are proprietăți puternice bactericide.<span class="consist__text--b">Ulei copacului de ceai </span> pătrunde adînc sub piele, tratează zonele cu probleme ale pielii, oferă efect răcoritor şi elimină mirosurile neplăcute după o zi stresantă de muncă. ',
    lt65: 'Crema de minune hidratează și hrănește pielea picioarelor, elimină  asprimea pielii, exfoliază, vindecă crăpăturile.',
    lt66: 'Spre deosebire de alte creme, «Tinedol» se distribuie uniform pe întreaga suprafață a tălpii. Se absoarbe repede și nu lasă urme pe haine și așternut. ',
    lt67: ' În ediţia limitată, am adăugat ulei de piatră. Se luptă eficient cu bătăturile. Dă pielii senzație de răcoare şi comfort după o zi grea.',
    lt68: 'O metodă simplă de a învinge <br>ciuperca, mîncărimea și crăpăturile!',
    lt69: 'Efect după 30 de zile <span class="title6-span1">de folosire a uleiului</span> «Tinedol»',
    lt70: 'Dispare ciuperca <br>tălpilor și unghiilor',
    lt71: 'Introduceţi datele dumneavoastră în formularul de mai jos',
    lt72: 'Trece mîncărimea și <br>exfolierea',
    lt73: 'Miros plăcut',
    lt74: 'Nu transpiră picioarele',
    lt75: 'Vindecă <br>crăpăturile',
    lt76: 'Voioșie şi confort <br>în timpul mișcării',
    lt77: 'Tălpi, <br>îngrijite și frumoase',
    lt78: 'Cum să se aplice <span class="title7-span1">crema «Tinedol»?</span>',
    lt79: ' Înainte de aplicare spălați cu săpun şi uscați bine picioarele. Aplicați un strat subtire de cremă pe toată talpa. Fiecare seară înainte de culcare timp de 30 de zile.<br> Veţi observa că calcîiele devin de culoare roz, iar pielea sănătoasă!',
    lt80: 'Cu ce crema «Tinedol» este mai bună decât alte medicamente antifungice?',
    lt81: 'Produsele antifungice se împart în două tipuri: primele nu sunt efective, altele acționează doar în timpul aplicării. Oamenii care suferă de ciuperca picioarelor, trebuie să utilizeze în mod constant creme şi unguente.',
    lt82: '«Tinedol» schimbă situația complet. Numeroase studii clinice au arătat că crema în mod eficient tratează ciuperca tălpilor şi unghiile. Deja după cursul 1 ciuperca trece și nu mai apare. Asemenea efect puternic se obține datorită ingredientelor natural din mediul înconjurător.',
    lt83: 'Părerea specialistului',
    lt84: 'Acest preparat demult și-a dovedit eficiența. Avantajul său principal - îngrijirea complexă. Chiar dacă nu aveți toate simptomele, ar ar trebui să începeți acum a folosi "Tinedol" pentru profilaxie. Ciuperca pe picioare se dezvoltă foarte repede! Astăzi aveţi o usoară exfoliere şi mâncărimi, iar mâine va trebui să vă internați în clinică și să beți antibiotice de 5 ori pe zi. Nu așteptați! Tratați problema acum. În afara de aceasta, ciuperca se transmite. În cazul în care v-ați îmbolnăvit dumneavoastră sau cineva apropiat, are de suferit întreaga familie!',
    lt85: '— Ştefan Coposh<br>к.м.н., CMMI N.A.Semașco. Medic -dermatolog, cosmetolog, micolog.',
    lt86: 'Comentarii',
    lt87: 'Pînă la «Tinedol» am crezut că ciuperca – ca ciupercile, dispar pe un timp, apoi apar din nou... Am încercat o mulțime de preparate. Simptomele dispăreau, iar ciuperca rămînea pe picior. Am fost nevoită să mă adresez medicului, el și mi-a prescris «Tinedol». De jumătate de an nu mă mai deranjează nimic. <br>Mulțumesc!',
    lt88: 'Nana, București',
    lt89: 'Tălpile, ca la nou-născut! Mereu merg la bazin. Cînd am aflat că am ciupercă, nu m-am mirat foarte tare, cabina de duș - comună, vestiar comun, clorul nu vă va salva de ciupercă. Dar ce e de făcut. La noi acolo toate fetele din vestiar știu, că mai bun preparat ca «Tinedol» nu este nimic! Toți ne aplicăm, dintre noi nici unul nu este bolnav!',
    lt90: 'Nicoletta, Brasov',
    lt91: 'Ciuperca se obișnuiește cu preparatele cu care vă lecuiți. La soț transpirau foarte tare picioarele, și ciuperca nu trecea din această cauză. Am ales «Tinedol» din două considerente. Deoarece acționează împotriva transpirației și a ciupercii. L-am folosit 3 luni. Totul a trecut!',
    lt92: 'Ecaterina, București',
    lt93: '',
    title2: 'Cumpără «Tinedol» cu preț redus. Prețuri, comentarii. Comandați «Tinedol» acum!',
};

function Translater() {
    for (class_name in new_lang) {
        var elements = document.getElementsByClassName(class_name);
        if (elements.length) {
            for (key in elements) {
                elements[key].innerHTML = new_lang[class_name];
            }
        }
    }
};